server:
  port: 8080 # –ì–ª–∞–≤–Ω—ã–π –ø–æ—Ä—Ç –Ω–∞—à–µ–≥–æ API

spring:
  application:
    name: search-service
  threads:
    virtual:
      enabled: true # üî• –ú–ê–ì–ò–Ø: –í–∫–ª—é—á–∞–µ–º –≤–∏—Ä—Ç—É–∞–ª—å–Ω—ã–µ –ø–æ—Ç–æ–∫–∏ –¥–ª—è –≤—Å–µ–≥–æ –≤–µ–±-—Å–µ—Ä–≤–µ—Ä–∞!

eureka:
  client:
    service-url:
      # –£–∫–∞–∑—ã–≤–∞–µ–º, –≥–¥–µ –∏—Å–∫–∞—Ç—å –Ω–∞—à Eureka Server
      defaultZone: http://localhost:8761/eureka/